### ISSUE TITLE
vagrant provision centos7-katello-{3.4,nightly} doesn't work with Ansible 2.4

### ISSUE THREAD

**Issue by kallies** [theforeman/forklift#530]
A `vagrant provision centos7-katello-{3.4,nightly}` doesn't work any more with Ansible 2.4 (tested on Ubuntu 16.04.3 LTS).

Git revision: 98447c3ce5c50042e785b93a9ca324f7d8661e7d
Ansible Version: 2.4.0.0-1ppa~xenial
OS: Ubuntu 16.04.3 LTS
Vagrant version: 1.8.7

Error message:

```
ERROR! Unexpected Exception, this is probably a bug: 'CallbackModule' object has no attribute 'set_options'
to see the full traceback, use -vvv
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

https://github.com/theforeman/forklift/blob/master/playbooks/callback_plugins/human_log.py#L30

For completeness the deprecation warning:

```
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 
'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.
 This feature will be removed in a future release. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is
 discouraged. The module documentation details page may explain more about this
 rationale.. This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

**Comment by kallies** [comment]
Related issue: https://github.com/ansible/ansible/issues/30597
